### ISSUE TITLE
Use SwiftUI

### ISSUE THREAD

**Issue by Xerxes249** [minvws/nl-covid19-notification-app-ios#2]
As the app is trivial, iOS 13.5+ is required, this is the perfect environment to use the new and modern SwiftUI. 

I believe choosing SwiftUI will save a lot of headaches and keeps the code a lot cleaner. 

#changemymind

**Comment by jeroenleenarts** [comment]
I don't agree. SwiftUI is "new tech" on Apple platforms. Come June it is to be expected that big changes are announced to SwiftUI. (Potential unwanted delays due to big platform changes.) Also the market adoption of SwiftUI is comparatively low. (This increases the barrier of entry for community observers.)

Personally I would also love to use SwiftUI on a project bigger then a lab test. Don't get me wrong on this. :)

**Comment by rm335** [comment]
We have discussed SwiftUI in the team. It is a bit too "new" for our project. Given the time pressure, we opt for some more classic approach. Many developers still make apps in everyday life that must support iOS 12 or lower and have therefore not been able to apply it in a big way. Although the iOS 13+ wish is a nice one to apply the latest, it unfortunately does not mean that all developers are already fully skilled in it. And then this is not the right project for "learning on the job".

**Comment by tom-wolters** [comment]
SwiftUI is not the right approach, I agree. I would consider an declarative approach like Texture/AsyncDiaplayKit though.

This will improve readability and working with git a lot.

**Comment by franklinvv** [comment]
On top of the reasons mentioned above, imho an additional reason not to use SwiftUI is because you also want to enable devices that do not have iOS 13 yet to install the app, and then guide them to the 13.5 update when they first launch the app. (Yes, some people just don't install updates.) And, who can tell whether Apple won't release an update for iOS 12 to include support for the GAEN API in the future?
