### ISSUE TITLE
2020-08-18: [VWS/Covid19NotificationApp] unclear call to action

### ISSUE THREAD

**Issue by donkersgoed** [minvws/nl-covid19-notification-app-ios#32]
### Describe the bug, issue or concern

The button to report that you've been tested positive is unclear / too technical.

The header states 'Share the GGD key'. Although this is undoubtedly what it technically does, it isn't what the user _wants_ to do. The user wants to report a positive test, so that's what the button should say.

Personally, I installed and opened the app because I want to help. I saw a button 'share' and felt like I wanted to share as much as possible, so I clicked it without properly reading the rest of the text. Before I knew it (and definitely because I didn't read well) I unintentionally reported a positive case.

### To Reproduce
1. Open the main screen of the application 

### Expected behavior
The button should say something like 'Report positive case'. Additionally, a dialog warning that a positive case will be reported as soon as you click 'continue' might be valuable.

### Screenshots

![76093AF5-3B3A-40A9-9409-88E2D886B0D8](https://user-images.githubusercontent.com/4188922/90512634-bbabdf00-e15e-11ea-81a1-b2e6066f21c3.jpeg)

**Smartphone (please complete the following information):**
 - Device: iPhone X
 - OS: 13.6

### Additional context
N/a

### Governance
- [x] I've read the contributing document https://github.com/minvws/.github/blob/master/CONTRIBUTING.md
- [x] I've read and understand the Code of Conduct https://github.com/minvws/.github/blob/master/CODE_OF_CONDUCT.md
- [x] I understand that any contributions or suggestions I made may make it into the actual code. I've read the License https://github.com/minvws/nl-covid19-notification-app-coordination/blob/master/LICENSE.txt and the contributor license agreement https://github.com/minvws/nl-covid19-notification-app-coordination/blob/master/CLA.md

**Comment by roelspruit** [comment]
Hi. Thanks for your report and our apologies for the late reply. 

Although I personally agree that the copy for this button can be a bit unclear, in this case this should not lead to issues because:

1. The "Share the GGD key" action will always be triggered by instructions given by the GGD on the phone (when you receive a notification of a positive test)
2. Even if a user would perform this action without a prompt from the GGD (like you did) it would not lead to any issues since performing the action without approval from the GGD will not result in people being notified. In other words, The GGD has to explicitly allow your "meldcode" to go through.

Because of this I'm going to close this issue. Thanks again for your feedback.
