### ISSUE TITLE
[2020-08-20]: [VWS/Covid19NotificationApp] iOS Background TEK check not working?

### ISSUE THREAD

**Issue by TeunVR** [minvws/nl-covid19-notification-app-ios#37]
### Describe the bug, issue or concern

I understood that yesterday the first batch of TEK keys was made available on the server.
Until this morning my "Blootstellingscontroles" list was empty.
When i launched the app the check was immediately performed and added to the list.
I thought the interval was 4 hours?

### To Reproduce
Install the app and wait for background TEK check.

### Expected behavior
I expected the TEK to be performed in the background.

### Platform
iPhone 11
iOS 13.6.1

### Additional context
I do have the German Corona-app installed, but it is not active

### Governance
- [x] I've read the contributing document https://github.com/minvws/.github/blob/master/CONTRIBUTING.md
- [x] I've read and understand the Code of Conduct https://github.com/minvws/.github/blob/master/CODE_OF_CONDUCT.md
- [x] I understand that any contributions or suggestions I made may make it into the actual code. I've read the License https://github.com/minvws/nl-covid19-notification-app-coordination/blob/master/LICENSE.txt and the contributor license agreement https://github.com/minvws/nl-covid19-notification-app-coordination/blob/master/CLA.md

**Comment by rvandijke** [comment]
Hi @TeunVR,

Thanks for raising this issue. Unfortunately, if it comes to background processing, we are limited by iOS launching CoronaMelder in the background. Technically, it's impossible to set an exact time interval to have the app launched in the background. iOS determines when it's the "right time" to launch and app in the background and have it do background processing. The only thing you can control is the duration you app does NOT need to be launched. This is the property `earliestBeginDate` on `BGAppRefreshTaskRequest`. We set that to the `refreshInterval` specified in the app's manifest (controlled by the background, but currently set to 4 hours). If no refreshInterval is available a default value of 60 minutes is currently used.

How iOS determines what the "right time" is, is a black box. It's based on battery, how frequently an app is used and many other factors. Apple did promise us though that for apps having the Exposure Notification entitlement, iOS will launch the app more frequently. We still don't know exact how frequent. In tests we have seen intervals from 30 minutes up to several hours. 

So, to conclude: If you let your app just sit in the background the TEKs will be processed at some point, but not exactly after 4 hours.

You can read more about background processing for iOS at https://developer.apple.com/documentation/backgroundtasks.

**Comment by TeunVR** [comment]
Yes i am aware of the background limitations, but this seems to be a pretty long time then.
I don't know when the keys were published yesterday, but until i launched manually at 8:23 this morning the app did not do a check. 
So it looks like at least 8 hours in this case.
My battery was full, not connected to charger by they way.
Was connected to WiFi.
Maybe Apple limits it to once every 24h then.

**Comment by MikeN123** [comment]
Same issue here, exposure was only checked yesterday at 13.28 when I launched the app, even though I had it installed from the beginning.

**Comment by TeunVR** [comment]
@rvandijke:
Console logging shows that the German app is running checks in the background and the Dutch app is nowhere to be seen.
It's been 4 days now since my last check (which was done when i launched the Dutch app manually, not in the background).
The Dutch CoronaMelder app is the active app in the settings.

This is the logging from dasd (DuetActivitySchedulerDaemon):
`bgProcessing-de.rki.coronawarnapp.exposure-notification:A0233E:[
	{name: DeviceActivityPolicy, policyWeight: 5.000, response: {Decision: Must Not Proceed, Score: 0.00, Rationale: [{launchType == PROCESSING AND deviceActive == 1}]}}
	{name: ThunderingHerdPolicy, policyWeight: 1.000, response: {Decision: Must Not Proceed, Score: 0.00, Rationale: [{timeSinceThunderingHerdTriggerEvent < 300}]}}
 ], FinalDecision: Must Not Proceed}`

The bluetoothd logging shows the Dutch app is transmitting, so that is working ok:
`nl.rijksoverheid.en-ENClient`

So it looks like the last installed Exposure Notification app is launched in the background instead of the currently active app.

**Comment by MikeN123** [comment]
Well, I do not have a second app installed, and background checks are not happening here either. So I don't think this is the full story. At the moment my last check shows 22/8 @ 9:21.

**Comment by rvandijke** [comment]
We've followed up with Apple and apparently the documentation is not 100% accurate.

https://developer.apple.com/documentation/exposurenotification/building_an_app_to_notify_users_of_covid-19_exposure says:

```
The app uses a background task to periodically check whether the user may have been exposed to an individual with COVID-19. The app’s Info.plist file declares a background task named com.example.apple-samplecode.ExposureNotificationSampleApp.exposure-notification. The BackgroundTask framework detects apps that contain the Exposure Notification entitlement and a background task that ends in exposure-notification. The operating system automatically launches these apps when they aren’t running and guarantees them more background time to ensure that the app can test and report results promptly.
```

We have several background tasks running, for the update process but also for sending decoy traffic and pushing a local notification that says the app is inactive. Because we meet the above requirements (correct entitlements, and have a task with an identifier that ends with exposure-notification) we were expected our app to be launched more frequently than 'regular' iOS behavior.

After following up with Apple we got the answer that only the task ending with `exposure-notification` is executed every 4 hours. The other tasks will be executed using the 'regular' behavior. 

We will create a fix to merge the update and "check status" logic in 1 single background task and ensure that tasks has the exposure-notification identifier. This should solve the update problem, as well as sending the 'inactive' notification (because the app should be updated now).

**Comment by MikeN123** [comment]
> have a task with an identifier that ends with exposure-notification

Are you sure? It seems it is in `BGTaskSchedulerPermittedIdentifiers`, but it is not actually used. So it may be that your original assumption is still correct, but it is not working because there is not actually an active task with `exposure-notification` in the name.

**Comment by rvandijke** [comment]
> > have a task with an identifier that ends with exposure-notification
> 
> Are you sure? It seems it is in `BGTaskSchedulerPermittedIdentifiers`, but it is not actually used. So it may be that your original assumption is still correct, but it is not working because there is not actually an active task with `exposure-notification` in the name.

You're correct, it's in the Info.plist but not scheduled. I think we can safely make the assumption here that it's not sufficient to meet the `and a background task that ends in exposure-notification` part of the documentation. 

This is on top of the list right now and a version with this fix will soon be released.

**Comment by TeunVR** [comment]
Good that it will be fixed asap, but i am a bit surprised that it was not seen before in any test?
The app has two main features: 
- broadcasting random ids (handled by iOS)
- checking exposure in the background (partly iOS, partly app)

One of the most important parts of the app is not implemented correctly and we only find it out now.
That makes me a bit uncomfortable actually.

**Comment by rvandijke** [comment]
> Good that it will be fixed asap, but i am a bit surprised that it was not seen before in any test?
> The app has two main features:
> 
> * broadcasting random ids (handled by iOS)
> * checking exposure in the background (partly iOS, partly app)
> 
> One of the most important parts of the app is not implemented correctly and we only find it out now.
> That makes me feel a bit uncomfortable actually.

I do understand your concern and I do agree that you ideally want to catch this during development. I do want to relate a bit however: processing exposures does work; it's the background processing that has issues (does not work as frequently as we want). Of course we did many tests during the development process but background processing is the hardest one to test and it takes the most amount of time as well. Also, the app is currently in "test & research" phase so I'm actually happy we are catching this now instead of in a few weeks later. 

On why this was not caught earlier:

We did test on iOS using lldb (see https://developer.apple.com/documentation/backgroundtasks/starting_and_terminating_tasks_during_development), but this unfortunately does not catch the above issue. Also, because we interact with the app a lot during testing and debugging (which increases the likelihood iOS launches your app in the background) we have also seen the app being launched in the background often and validated that processing works when you do not launch the app to the foreground.

These are not excuses, just reasons why the issue was not caught before. I hope this answers your question and will take away some of the concerns you're having. Thanks again for being on top of this and for creating the issue on Github!

**Comment by TeunVR** [comment]
Yes testing background processing on iOS is tricky. I usually fall back to logging in that situation.
Good that it will be fixed soon 👍🏻

**Comment by rvandijke** [comment]
The fix is now released in 1.0.5. Thanks for raising the issue!

**Comment by TeunVR** [comment]
I updated this morning and did not launch the app yet.
Just to test if the problem fixes itself or needs at least one app launch.
No background check yet :) Last check is yesterday at 11:42.

**Comment by rvandijke** [comment]
Please give it 4 hours, that's the minimum interval we specified. Also you might need to launch the app once to reschedule the background tasks correctly as we've changed the background task identifiers.

**Comment by TeunVR** [comment]
That is what i was assuming. I will wait a bit longer, but it's been 4 hours already.
So current users need to launch the app at least once after update, unfortunate but i guess it's necessary.

**Comment by TeunVR** [comment]
Well looks like it is still not working here :(
Last check yesterday 16:04, when i manually launched the updated app.
I would expect to see checks every 4 hours approximately right?
Battery is full. 
iPhone 11 13.7

**Comment by rvandijke** [comment]
We've had multiple reports internally (which were validated by eng) that background processing is working now. We'll validate once again on iOS 13.7. I'll come back to this.

It also might be that no new checks show up as no new exposure keysets were available. The last keyset was released yesterday at 14:10 so that seems to be inline with why you haven't seen any exposure check yet.

**Comment by MikeN123** [comment]
I upgraded to iOS 13.7. Without launching the app, it did not do any checks, even after restarting the phone.

When I launched the app, it did a check, yesterday at 19:09. Today, it did a background check, at 15:15. So for me it at least seems to do something now.

**Comment by TeunVR** [comment]
I got a background check at 16:08 today.
Seems to work 👍🏻

**Comment by rvandijke** [comment]
> I got a background check at 16:08 today.
> Seems to work 👍🏻

Awesome, thanks for confirming!
