### ISSUE TITLE
[DATE]: [VWS/Covid19NotificationApp] CoronaMelder app drains iPhone battery

### ISSUE THREAD

**Issue by berendengelbrecht** [minvws/nl-covid19-notification-app-ios#43]
### Describe the bug, issue or concern

Since installing the CoronaMelder app, the battery of my iPhone 8 no longer lasts a full working day. The battery is fairly new - the phone claims that the battery is at 93% of the original capacity.

When I looked at battery consumption details after receiving a "battery low" warning, it showed 48% "Gezondheid - Blootstelling aan COVID-19". Now -while charging- that is even 75%.
I am using latest iOS release 13.6.1 (recently updated).

Worse even: when I checked the app, it claimed that it was inactive because it couldn't connect to the internet in the past 24 hours (other background apps like DropBox did not have a problem with that).

I found the identical issue for the German Corona-Warn-App, here:
https://github.com/corona-warn-app/cwa-app-ios/issues/671

### To Reproduce
1. Install the CoronaMelder on an iPhone 8 having latest iOS 13.6.1
2. Don't do anything with the app. Do not come near other people/phones for more than 30 minutes during a 12 hour period.
3. Check the battery consumption (settings > battery > battery usage per app) after 12 hours.
4. Note that the Health - COVID-19 category is the #1 battery consumer, although it should have been mostly inactive 

### Expected behavior
The Health - COVID-19 backend should consume much less power when the phone hardly comes near other phones and certainly when the front-end app is not even active.

### Screenshots
![2020-08-26 18 25 37](https://user-images.githubusercontent.com/4265924/91331100-9f491b80-e7ca-11ea-8928-d225546af162.png)
![2020-08-26 18 25 46](https://user-images.githubusercontent.com/4265924/91331115-a4a66600-e7ca-11ea-9b2e-0b85d8654a44.png)
![2020-08-26 18 28 14](https://user-images.githubusercontent.com/4265924/91331136-aa03b080-e7ca-11ea-9a54-b599583d3b15.png)

**Smartphone (please complete the following information):**
 - Device: iPhone8
 - OS: iOS 13.6.1
 - Browser N/A
 - Version 1.0.4

### Governance
- [x] I've read the contributing document https://github.com/minvws/.github/blob/master/CONTRIBUTING.md
- [x] I've read and understand the Code of Conduct https://github.com/minvws/.github/blob/master/CODE_OF_CONDUCT.md
- [x] I understand that any contributions or suggestions I made may make it into the actual code. I've read the License https://github.com/minvws/nl-covid19-notification-app-coordination/blob/master/LICENSE.txt and the contributor license agreement https://github.com/minvws/nl-covid19-notification-app-coordination/blob/master/CLA.md

**Comment by erikgaal** [comment]
Hi there,

Please be aware that the battery usage of `Exposure Notifications` is not related to the `Coronamelder` app or its battery usage.

Has the battery life improved for you since the public release of iOS 14? On my iPhone 11 Pro, it used only 4% in the last 10 days.

**Comment by berendengelbrecht** [comment]
Hi Erik,

Thanks for answering. I did realize that CoronaMelder is just a frontend
and the backend by Apple was the problem, but still I could only raise an
issue at the first line. To complain to Apple as a consumer is painfully
difficult.
Yes, it has improved. I was in Germany for a week and the Corona-Warn-App
works fine too.

Thanks and best regards,

Berend


Op do 15 okt. 2020 om 14:31 schreef Erik Gaal <notifications@github.com>:

**Comment by reinier** [comment]
We've been investigating battery usage of CoronaMelder for quit some time and we haven't seen an unusual amount of battery drain from the app.

**Comment by herkocoomans** [comment]
Not sure if this should be put here, but if not related to CoronaMelder directly, you could pass it on to Apple for further investigation.

Device info: iPhone 11 Pro, iOS 14.2.

Description: since iOS 14.2 the Exposure Notification service on my phone uses on average 18% battery power over 10 days of measuring. This results in the phone draining _while being recharged_, shutting down due to low power, booting back up again. 
![image](https://user-images.githubusercontent.com/979424/100542844-e244e000-324c-11eb-8953-5cfa9046ef73.png)
![image](https://user-images.githubusercontent.com/979424/100542846-e8d35780-324c-11eb-9b06-b27a3f6fd4eb.png)

I've contacted Apple Support and they suggest doing factory reset and reinstall everything one by one (not from backup) to find out where the problem lies. But it's with the exposure notification, obviously. Apple Support did a full diagnostics of the phone (over the air) and couldn't find anything wrong with hard- or software.

I've updated the CoronaMelder app to the latest and greatest in the AppStore.

The battery monitoring referred to above in this issue is most likely done on iOS 14.0/.1, so maybe there's a problem in how 14.2 deals with this?
